# Generated by Django 5.1.6 on 2025-02-16 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarysettings',
            name='nutrient_targets',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='diet.nutritiondata'),
        ),
        migrations.AddField(
            model_name='diarysettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='diary_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.diarysettings'),
        ),
    ]
