# Generated by Django 5.1.4 on 2024-12-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarysettings',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
    ]
