# Generated by Django 5.1.2 on 2024-11-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nutrition_goals',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='diet.nutritiondata'),
        ),
    ]
