# Generated by Django 5.1.2 on 2024-11-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_nutrition_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
