# Generated by Django 5.1.2 on 2024-11-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_budget'),
        ('diet', '0003_rename_cholestherol_nutritiondata_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nutrition_goals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='diet.nutritiondata'),
        ),
    ]
