# Generated by Django 5.1.2 on 2024-11-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_nutrition_goals'),
        ('diet', '0004_alter_foodproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nutrition_goals',
        ),
        migrations.CreateModel(
            name='DiarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('nutrient_goals', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='diet.nutritiondata')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dairy_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.diarysettings'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('diary_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.diarysettings')),
            ],
        ),
    ]
