# Generated by Django 5.1.2 on 2024-11-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_budget_remove_user_nutrition_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dairy_settings',
            new_name='diary_settings',
        ),
    ]
