# Generated by Django 5.1.2 on 2024-11-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_diarysettings_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarysettings',
            old_name='nutrient_goals',
            new_name='nutrient_targets',
        ),
    ]
