# Generated by Django 5.1.2 on 2024-11-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_nutrient_goals_diarysettings_nutrient_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='hide_from_dairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
