# Generated by Django 5.1.2 on 2024-11-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_meal_hide_from_dairy_alter_meal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='hide_from_dairy',
            new_name='hide_from_diary',
        ),
    ]
