# Generated by Django 5.1.2 on 2024-11-05 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('starch', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('added_sugars', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monounsaturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('polyunsaturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trans_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('choline', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('folate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('a', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('c', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('d', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('k', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calcium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chromium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('copper', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iron', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('magnesium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manganese', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('molybdenum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phosphorus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potassium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selenium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zinc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('product_link', models.URLField(null=True)),
                ('img_url', models.URLField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('servings', models.IntegerField(default=1)),
                ('serving_measure', models.CharField(default='serving', max_length=20)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nutrition_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_product', to='diet.nutritiondata')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('productsQuantity', models.JSONField()),
                ('days', models.JSONField()),
                ('foodProducts', models.ManyToManyField(to='diet.foodproduct')),
            ],
        ),
    ]
