# Generated by Django 5.1.2 on 2024-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='serving_measure',
            field=models.CharField(default='serving', max_length=20),
        ),
    ]
