# Generated by Django 5.1.2 on 2024-11-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritiondata',
            old_name='cholesterol',
            new_name='cholestherol',
        ),
    ]
