# Generated by Django 5.1.2 on 2024-11-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_rename_cholesterol_nutritiondata_cholestherol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritiondata',
            old_name='cholestherol',
            new_name='cholesterol',
        ),
    ]
