# Generated by Django 5.1.2 on 2024-11-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_foodproduct_serving_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
