# Generated by Django 5.1.2 on 2024-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietplan_created_at_dietplan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='budget',
            field=models.FloatField(null=True),
        ),
    ]
