# Generated by Django 5.1.2 on 2024-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_foodproduct_a_alter_foodproduct_added_sugars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
