# Generated by Django 5.1.2 on 2024-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_foodproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
