# Generated by Django 5.1.2 on 2024-12-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_foodproduct_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='days',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='productsQuantity',
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diet.dietplan')),
            ],
        ),
        migrations.CreateModel(
            name='DietDayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietday')),
                ('foods', models.ManyToManyField(to='diet.foodproduct')),
            ],
        ),
    ]
