# Generated by Django 5.1.4 on 2024-12-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_foodproduct_price_alter_foodproduct_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='serving_size',
            field=models.FloatField(null=True),
        ),
    ]
